/**
 * CreateProjectDialog - Modal per creazione nuovo progetto
 *
 * Features:
 * - Form guidato per creare nuovo progetto
 * - Selezione database mode (SQLite/PostgreSQL/Hybrid)
 * - Configurazione dinamica in base al mode selezionato
 * - Validazione input
 * - Upload database SQLite esistente (opzionale)
 * - Feedback errori e successo
 */
import { useState, useContext } from 'react';
import { ProjectContext } from '../context/ProjectContext';
import TeamManagement from './TeamManagement';
import '../styles/CreateProjectDialog.css';

const CreateProjectDialog = ({ isOpen, onClose }) => {
  const { createProject } = useContext(ProjectContext);

  const [formData, setFormData] = useState({
    name: '',
    description: '',
    db_mode: 'sqlite'
  });

  // SQLite config
  const [sqliteConfig, setSqliteConfig] = useState({
    use_existing: false,
    db_file: null
  });

  // PostgreSQL config
  const [postgresConfig, setPostgresConfig] = useState({
    host: 'localhost',
    port: 5432,
    database: '',
    user: '',
    password: ''
  });

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [step, setStep] = useState(1); // Step 1: Basic info, Step 2: DB config, Step 3: Share (optional)
  const [createdProject, setCreatedProject] = useState(null); // Store created project for step 3

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
    setError(null);
  };

  const handleDbModeChange = (mode) => {
    setFormData(prev => ({ ...prev, db_mode: mode }));
    setError(null);
  };

  const handlePostgresChange = (e) => {
    const { name, value } = e.target;
    setPostgresConfig(prev => ({
      ...prev,
      [name]: name === 'port' ? parseInt(value) : value
    }));
  };

  const handleFileUpload = (e) => {
    const file = e.target.files[0];
    if (file && file.name.endsWith('.sqlite')) {
      setSqliteConfig(prev => ({
        ...prev,
        db_file: file,
        use_existing: true
      }));
      setError(null);
    } else {
      setError('Please upload a valid SQLite database file (.sqlite)');
    }
  };

  const validateStep1 = () => {
    if (!formData.name.trim()) {
      setError('Project name is required');
      return false;
    }
    return true;
  };

  const validateStep2 = () => {
    if (formData.db_mode === 'postgres' || formData.db_mode === 'hybrid') {
      if (!postgresConfig.database || !postgresConfig.user || !postgresConfig.password) {
        setError('PostgreSQL configuration incomplete');
        return false;
      }
    }
    return true;
  };

  const handleNext = () => {
    if (validateStep1()) {
      setStep(2);
    }
  };

  const handleBack = () => {
    setStep(1);
    setError(null);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validateStep2()) {
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Prepara payload basato su db_mode
      const payload = {
        name: formData.name,
        description: formData.description,
        db_mode: formData.db_mode
      };

      if (formData.db_mode === 'sqlite') {
        payload.sqlite_config = {
          path: null // Auto-generated by backend
        };
      } else if (formData.db_mode === 'postgres') {
        payload.postgres_config = postgresConfig;
      } else if (formData.db_mode === 'hybrid') {
        payload.postgres_config = postgresConfig;
      }

      const result = await createProject(payload);

      if (result.success) {
        // Se c'è un file SQLite da caricare, fallo dopo la creazione
        if (sqliteConfig.db_file && formData.db_mode === 'sqlite') {
          await uploadDatabase(result.project.id, sqliteConfig.db_file);
        }

        // Store project and move to step 3 (team management)
        setCreatedProject(result.project);
        setStep(3);
      } else {
        setError(result.error || 'Failed to create project');
      }
    } catch (err) {
      console.error('Create project error:', err);
      setError(err.response?.data?.detail || 'Failed to create project');
    } finally {
      setLoading(false);
    }
  };

  const uploadDatabase = async (projectId, file) => {
    try {
      const formData = new FormData();
      formData.append('file', file);

      const response = await api.post(`/projects/${projectId}/upload-db`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data'
        }
      });

      if (response.data.success) {
        console.log('Database uploaded successfully:', response.data.message);
      } else {
        throw new Error(response.data.detail || 'Failed to upload database');
      }
    } catch (err) {
      console.error('Upload database error:', err);
      // Non bloccare la creazione del progetto se l'upload fallisce
      // L'utente può ricaricare il DB in seguito
    }
  };

  const resetForm = () => {
    setFormData({
      name: '',
      description: '',
      db_mode: 'sqlite'
    });
    setSqliteConfig({
      use_existing: false,
      db_file: null
    });
    setPostgresConfig({
      host: 'localhost',
      port: 5432,
      database: '',
      user: '',
      password: ''
    });
    setStep(1);
    setError(null);
  };

  const handleClose = () => {
    resetForm();
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="dialog-backdrop" onClick={handleClose}>
      <div className="create-project-dialog" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="dialog-header">
          <h2>Create New Project</h2>
          <button
            className="close-btn"
            onClick={handleClose}
            disabled={loading}
          >
            ✕
          </button>
        </div>

        {/* Progress Indicator */}
        <div className="progress-steps">
          <div className={`step ${step >= 1 ? 'active' : ''}`}>
            <span className="step-number">1</span>
            <span className="step-label">Basic Info</span>
          </div>
          <div className="step-divider"></div>
          <div className={`step ${step >= 2 ? 'active' : ''}`}>
            <span className="step-number">2</span>
            <span className="step-label">Database</span>
          </div>
          <div className="step-divider"></div>
          <div className={`step ${step >= 3 ? 'active' : ''}`}>
            <span className="step-number">3</span>
            <span className="step-label">Share</span>
          </div>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit}>
          {/* Step 1: Basic Information */}
          {step === 1 && (
            <div className="dialog-body">
              <div className="form-group">
                <label htmlFor="name">Project Name *</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleInputChange}
                  placeholder="My Archaeological Project"
                  required
                  autoFocus
                />
              </div>

              <div className="form-group">
                <label htmlFor="description">Description</label>
                <textarea
                  id="description"
                  name="description"
                  value={formData.description}
                  onChange={handleInputChange}
                  placeholder="Describe your project..."
                  rows={3}
                />
              </div>

              <div className="form-group">
                <label>Database Mode *</label>
                <div className="db-mode-options">
                  <button
                    type="button"
                    className={`mode-option ${formData.db_mode === 'sqlite' ? 'active' : ''}`}
                    onClick={() => handleDbModeChange('sqlite')}
                  >
                    <div className="mode-icon">💾</div>
                    <div className="mode-title">SQLite</div>
                    <div className="mode-description">
                      Local file database. Best for single-user offline work.
                    </div>
                  </button>

                  <button
                    type="button"
                    className={`mode-option ${formData.db_mode === 'postgres' ? 'active' : ''}`}
                    onClick={() => handleDbModeChange('postgres')}
                  >
                    <div className="mode-icon">🐘</div>
                    <div className="mode-title">PostgreSQL</div>
                    <div className="mode-description">
                      Centralized database. Best for team collaboration.
                    </div>
                  </button>

                  <button
                    type="button"
                    className={`mode-option ${formData.db_mode === 'hybrid' ? 'active' : ''}`}
                    onClick={() => handleDbModeChange('hybrid')}
                  >
                    <div className="mode-icon">🔀</div>
                    <div className="mode-title">Hybrid</div>
                    <div className="mode-description">
                      Shared PostgreSQL with row-level isolation.
                    </div>
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Step 2: Database Configuration */}
          {step === 2 && (
            <div className="dialog-body">
              {formData.db_mode === 'sqlite' && (
                <div className="config-section">
                  <h3>SQLite Configuration</h3>
                  <p className="config-description">
                    A new SQLite database will be created automatically.
                    Optionally, you can upload an existing database file.
                  </p>

                  <div className="form-group">
                    <label htmlFor="db-file">Upload Existing Database (Optional)</label>
                    <div className="file-upload">
                      <input
                        type="file"
                        id="db-file"
                        accept=".sqlite,.db"
                        onChange={handleFileUpload}
                      />
                      {sqliteConfig.db_file && (
                        <div className="file-info">
                          Selected: {sqliteConfig.db_file.name}
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              )}

              {(formData.db_mode === 'postgres' || formData.db_mode === 'hybrid') && (
                <div className="config-section">
                  <h3>PostgreSQL Configuration</h3>
                  <p className="config-description">
                    Connect to an existing PostgreSQL database.
                    {formData.db_mode === 'hybrid' && ' Row-level security will be enabled automatically.'}
                  </p>

                  <div className="form-row">
                    <div className="form-group">
                      <label htmlFor="pg-host">Host *</label>
                      <input
                        type="text"
                        id="pg-host"
                        name="host"
                        value={postgresConfig.host}
                        onChange={handlePostgresChange}
                        placeholder="localhost"
                        required
                      />
                    </div>

                    <div className="form-group">
                      <label htmlFor="pg-port">Port *</label>
                      <input
                        type="number"
                        id="pg-port"
                        name="port"
                        value={postgresConfig.port}
                        onChange={handlePostgresChange}
                        placeholder="5432"
                        required
                      />
                    </div>
                  </div>

                  <div className="form-group">
                    <label htmlFor="pg-database">Database Name *</label>
                    <input
                      type="text"
                      id="pg-database"
                      name="database"
                      value={postgresConfig.database}
                      onChange={handlePostgresChange}
                      placeholder="pyarchinit_db"
                      required
                    />
                  </div>

                  <div className="form-group">
                    <label htmlFor="pg-user">Username *</label>
                    <input
                      type="text"
                      id="pg-user"
                      name="user"
                      value={postgresConfig.user}
                      onChange={handlePostgresChange}
                      placeholder="postgres"
                      required
                    />
                  </div>

                  <div className="form-group">
                    <label htmlFor="pg-password">Password *</label>
                    <input
                      type="password"
                      id="pg-password"
                      name="password"
                      value={postgresConfig.password}
                      onChange={handlePostgresChange}
                      placeholder="••••••••"
                      required
                    />
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Step 3: Team Management (Optional) */}
          {step === 3 && createdProject && (
            <div className="dialog-body">
              <div className="success-message" style={{ marginBottom: '1.5rem' }}>
                ✅ Project "{createdProject.name}" created successfully!
              </div>
              <p style={{ marginBottom: '1.5rem', color: 'rgba(255, 255, 255, 0.8)' }}>
                You can now invite team members to collaborate on this project.
                This step is optional - you can skip it and invite members later.
              </p>
              <TeamManagement
                projectId={createdProject.id}
                currentUserRole="owner"
                onClose={null}
              />
            </div>
          )}

          {/* Error Display */}
          {error && (
            <div className="error-message">
              {error}
            </div>
          )}

          {/* Footer / Actions */}
          <div className="dialog-footer">
            {step === 1 && (
              <>
                <button
                  type="button"
                  className="btn-secondary"
                  onClick={handleClose}
                  disabled={loading}
                >
                  Cancel
                </button>
                <button
                  type="button"
                  className="btn-primary"
                  onClick={handleNext}
                  disabled={loading}
                >
                  Next
                </button>
              </>
            )}

            {step === 2 && (
              <>
                <button
                  type="button"
                  className="btn-secondary"
                  onClick={handleBack}
                  disabled={loading}
                >
                  Back
                </button>
                <button
                  type="submit"
                  className="btn-primary"
                  disabled={loading}
                >
                  {loading ? 'Creating...' : 'Create Project'}
                </button>
              </>
            )}

            {step === 3 && (
              <>
                <button
                  type="button"
                  className="btn-secondary"
                  onClick={() => {
                    onClose();
                    resetForm();
                  }}
                  disabled={loading}
                >
                  Skip for Now
                </button>
                <button
                  type="button"
                  className="btn-primary"
                  onClick={() => {
                    onClose();
                    resetForm();
                  }}
                  disabled={loading}
                >
                  Done
                </button>
              </>
            )}
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreateProjectDialog;
